apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret-example
  namespace: default
spec:
  refreshInterval: 10m # Time to refresh the secret
  secretStoreRef:
    name: secretstore-sample # Name of the SecretStore
    kind: SecretStore
  target:
    name: kube-secret # Name of the K8s Secret to create
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: DB_CREDENTIALS
  # - secretKey: api-key # Key in the Kubernetes Secret
  #   remoteRef:
  #     key: prod/api-key # Key in the External API
  #     property: api-key # Optional: property within the secret
