apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
  namespace: default # SecretStores are namespaced
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-2
      auth:
        secretRef:
          # Refers to a standard Kubernetes Secret that holds the authentication credentials for AWS
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
